using GridRunner.InputModule.Signals;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;

namespace GridRunner.InputModule
{
    public class InputManager : MonoBehaviour
    {
        void Update()
        {
            if (Input.GetMouseButtonDown(0) && !IsPointerOverUIElement())
            {
                InputSignals.Instance.onClick?.Invoke();
            }
        }
        private bool IsPointerOverUIElement()
        {
            var eventData = new PointerEventData(EventSystem.current);
            eventData.position = Input.mousePosition;
            var results = new List<RaycastResult>();
            EventSystem.current.RaycastAll(eventData, results);
            return results.Count > 0;
        }
    }
}
